version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: clegrof/home-library-service:latest
    container_name: home-library-service
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=home_library
    networks:
      - home-library-network

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    image: clegrof/home-library-postgres:latest
    container_name: home-library-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=home_library
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - home-library-network

networks:
  home-library-network:
    driver: bridge

volumes:
  postgres_data:
